version: '2'
volumes:
    database_data:
        driver: local
services:
  nginx:
      image: nginx:latest
      ports:
          - 8888:80
      volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      volumes_from:
          - php
  php:
      build: ./docker/php/
      expose:
          - 9000
      volumes:
          - .:/var/web
      links:
         - mysql
  mysql:
      image: mysql:latest
      expose:
          - 3306
      volumes:
          - database_data:/var/lib/mysql
          - ./docker/mysql/conf.d:/etc/mysql/conf.d
      networks:
          default:
              aliases:
                  - localhost
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: drupal
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
